# install-docker.yml
- hosts: tools
  become: yes
  tasks:
    - name: Remove conflicting packages
      shell: |
        for pkg in docker.io docker-doc docker-compose docker-compose-v2 podman-docker containerd runc; do
          apt-get remove -y $pkg
        done

    - name: Install required packages
      apt:
        name: 
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Add Docker's official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present

    - name: Update apt package index
      apt:
        update_cache: yes

    - name: Install Docker CE and Docker Compose
      apt:
        name: 
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present

    - name: Ensure Docker service is started and enabled
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Add ansible user to docker group
      user:
        name: "{{ ansible_user }}"
        group: docker
        append: yes
