---
- hosts: masters, workers
  become: yes
  vars:
    k3s_version: "v1.31.2+k3s1"
    ha_mode: true # Jika true, cluster akan dijalankan dalam mode HA
    k3s_token: "a2354ksdf34efwjad87324bhjdu3rtkj39hj"
  roles:
    - role: common
    - role: k3s

- hosts: "{{ groups['masters'][0] }}" # Hanya di master pertama
  become: yes
  vars:
    rancher_version: "2.7.0"
  roles:
    - role: helm
    - role: helm_chart
    # - role: rancher # Role Rancher hanya diinstal di satu master node
