version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: vault
      POSTGRES_PASSWORD: ajhd734hdkallf
      POSTGRES_DB: vault
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready'"]
      interval: 10s
      timeout: 3s
      retries: 3
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data

  vault:
    image: hashicorp/vault:latest
    container_name: vault
    restart: unless-stopped
    ports:
      - "8200:8200"
    environment:
      VAULT_ADDR: "http://0.0.0.0:8200"
    volumes:
      - ./vault/config:/vault/config
      - ./vault/unseal:/vault/unseal
      - ./vault/entrypoint.sh:/vault/entrypoint.sh
    entrypoint: ["sh", "-c", "vault server -config=/vault/config/vault.hcl"]
    depends_on:
      postgres:
        condition: service_healthy
