---
- name: Check if K3s is installed
  stat:
    path: /usr/local/bin/k3s
  register: k3s_installed

- name: Uninstall K3s if installed
  shell: /usr/local/bin/k3s-uninstall.sh
  when: k3s_installed.stat.exists
  ignore_errors: yes

- name: Remove leftover K3s files
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /usr/local/bin/k3s
    - /usr/local/bin/k3s-uninstall.sh
    - /etc/rancher
    - /var/lib/rancher
  when: k3s_installed.stat.exists

# Jika ha_mode == true dan ini adalah master pertama, gunakan --cluster-init
- name: Install K3s on first master node with cluster-init in HA mode
  shell: |
    curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION={{ k3s_version }} sh -s - server --cluster-init
  when: ha_mode and inventory_hostname == groups['masters'][0]
  args:
    creates: /usr/local/bin/k3s

# Jika tidak dalam HA mode (hanya satu master), instal K3s tanpa --cluster-init
- name: Install K3s on first and only master node in non-HA mode
  shell: |
    curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION={{ k3s_version }} sh -s - server
  when: not ha_mode and inventory_hostname == groups['masters'][0]
  args:
    creates: /usr/local/bin/k3s

# Ambil token K3s untuk node master lain jika dalam HA mode
- name: Get K3s token
  slurp:
    src: /var/lib/rancher/k3s/server/node-token
  register: k3s_token_raw
  when: ha_mode and inventory_hostname == groups['masters'][0]

- name: Set K3s token fact
  set_fact:
    k3s_token: "{{ k3s_token_raw.content | b64decode }}"
  when: ha_mode and inventory_hostname == groups['masters'][0]

- name: Get master node IP
  command: hostname -I
  register: master_ip_raw
  when: inventory_hostname == groups['masters'][0]

- name: Set master IP fact
  set_fact:
    master_ip: "{{ master_ip_raw.stdout.split()[0] }}"
  when: inventory_hostname == groups['masters'][0]

# Instal K3s di master lain jika ha_mode == true
- name: Install K3s on other master nodes in HA mode
  shell: |
    curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION={{ k3s_version }} K3S_TOKEN={{ hostvars['master1'].k3s_token }} sh -s - server --server https://{{ hostvars['master1'].master_ip }}:6443
  when: ha_mode and inventory_hostname != groups['masters'][0]
  args:
    creates: /usr/local/bin/k3s

# Instal agen K3s di node worker
- name: Install K3s agent on worker nodes
  shell: |
    curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION={{ k3s_version }} K3S_TOKEN={{ hostvars['master1'].k3s_token }} sh -s - agent --server https://{{ hostvars['master1'].master_ip }}:6443
  when: inventory_hostname in groups['workers']
  args:
    creates: /usr/local/bin/k3s-agent

- name: Install Metrics Server
  become: yes
  command: kubectl apply -f https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml
  when: inventory_hostname == groups['masters'][0]
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml
